#!/usr/bin/env bash
cd `dirname $0`

source virtualenvwrapper.sh

function check_worked {
    if ! $*
    then
        exit 1
    fi
}

check_worked python setup.py sdist upload
rm -r dist django_slumber.egg-info
