#!/usr/bin/env bash
cd `dirname $0`

source virtualenvwrapper.sh

function check_worked {
    if ! $*
    then
        exit 1
    fi
}

workon slumber1-0
cd test-projects/django1_0
check_worked python manage.py test slumber_test

workon slumber1-3
cd ../django1_3
check_worked python manage.py test slumber_test \
        --with-coverage --cover-erase \
        --cover-package=slumber --cover-package=slumber_test

cd ../..
check_worked pylint --rcfile=pylintrc --output-format=colorized slumber
