#!/usr/bin/env bash
cd `dirname $0`

source virtualenvwrapper.sh

function check_worked {
    if ! $*
    then
        exit 1
    fi
}

mkvirtualenv --no-site-packages slumber1-0
check_worked pip install -r setup.pip -r django1_0/setup.pip
deactivate

mkvirtualenv --no-site-package slumber1-3
check_worked pip install -r setup.pip -r django1_3/setup.pip
deactivate

# mkvirtualenv --no-site-package slumber1-3_psycopg2-4-1
# check_worked pip install -r setup.pip -r django1_3_psycopg2_4_1/setup.pip
# deactivate

mkvirtualenv --no-site-package slumber1-4
check_worked pip install -r setup.pip -r django1_4/setup.pip
deactivate

# mkvirtualenv --no-site-package slumber1-4_psycopg2-4-1
# check_worked pip install -r setup.pip -r django1_4_psycopg2_4_1/setup.pip
# deactivate

mkvirtualenv --no-site-package slumber1-5
check_worked pip install -r setup.pip -r django1_5/setup.pip
deactivate
